
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SUBJECT_LIST_REQUEST = 'SUBJECT_LIST_REQUEST'
export const SUBJECT_LIST_SUCCESS = 'SUBJECT_LIST_SUCCESS'
export const SUBJECT_LIST_FAILURE = 'SUBJECT_LIST_FAILURE'

export const SUBJECT_INDEX_REQUEST = 'SUBJECT_INDEX_REQUEST'
export const SUBJECT_INDEX_SUCCESS = 'SUBJECT_INDEX_SUCCESS'
export const SUBJECT_INDEX_FAILURE = 'SUBJECT_INDEX_FAILURE'

export const COOLDOWN_SKIP_REQUEST = 'COOLDOWN_SKIP_REQUEST'
export const COOLDOWN_SKIP_SUCCESS = 'COOLDOWN_SKIP_SUCCESS'
export const COOLDOWN_SKIP_FAILURE = 'COOLDOWN_SKIP_FAILURE'



// The list of concepts to study
export const CONCEPT_LIST_REQUEST = 'CONCEPT_LIST_REQUEST'
export const CONCEPT_LIST_SUCCESS = 'CONCEPT_LIST_SUCCESS'
export const CONCEPT_LIST_FAILURE = 'CONCEPT_LIST_FAILURE'

// Single Concept
export const CONCEPT_VIEW_REQUEST = 'CONCEPT_VIEW_REQUEST'
export const CONCEPT_VIEW_SUCCESS = 'CONCEPT_VIEW_SUCCESS'
export const CONCEPT_VIEW_FAILURE = 'CONCEPT_VIEW_FAILURE'

export const TOGGLE_REFERENCES = 'TOGGLE_REFERENCES'
export const READ_CONCEPT = 'READ_CONCEPT'
export const SHOW_ANSWER = 'SHOW_ANSWER'

// Set mode of conceptReader 
export const SET_MODE = 'SET_MODE'


export const MARK_CONCEPT = 'MARK_CONCEPT'

// The Actions performed on concepts
export const CONCEPT_SKIP = 'CONCEPT_SKIP'
export const CONCEPT_READ = 'CONCEPT_READ'
export const CONCEPT_RIGHT = 'CONCEPT_RIGHT'
export const CONCEPT_WRONG = 'CONCEPT_WRONG'

export const SUBMIT_RESULT_REQUEST = 'SUBMIT_RESULT_REQUEST'
export const SUBMIT_RESULT_SUCCESS = 'SUBMIT_RESULT_SUCCESS'
export const SUBMIT_RESULT_FAILURE = 'SUBMIT_RESULT_FAILURE'

export const REDEEM_CODE_REQUEST = 'REDEEM_CODE_REQUEST'
export const REDEEM_CODE_SUCCESS = 'REDEEM_CODE_SUCCESS'
export const REDEEM_CODE_FAILURE = 'REDEEM_CODE_FAILURE'

export const OFFLINE_INDEX_REQUEST = 'OFFLINE_INDEX_REQUEST'
export const OFFLINE_INDEX_SUCCESS = 'OFFLINE_INDEX_SUCCESS'
export const OFFLINE_INDEX_FAILURE = 'OFFLINE_INDEX_FAILURE'