export const SET_AUTH = 'SET_AUTH'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const SUBJECT_LIST_REQUEST = 'SUBJECT_LIST_REQUEST'
export const SUBJECT_LIST_SUCCESS = 'SUBJECT_LIST_SUCCESS'
export const SUBJECT_LIST_FAILURE = 'SUBJECT_LIST_FAILURE'

export const SUBJECT_DETAIL_REQUEST = 'SUBJECT_DETAIL_REQUEST'
export const SUBJECT_DETAIL_SUCCESS = 'SUBJECT_DETAIL_SUCCESS'
export const SUBJECT_DETAIL_FAILURE = 'SUBJECT_DETAIL_FAILURE'

export const CHAPTER_LIST_REQUEST = 'CHAPTER_LIST_REQUEST'
export const CHAPTER_LIST_SUCCESS = 'CHAPTER_LIST_SUCCESS'
export const CHAPTER_LIST_FAILURE = 'CHAPTER_LIST_FAILURE'

export const CONCEPT_LIST_REQUEST = 'CONCEPT_LIST_REQUEST'
export const CONCEPT_LIST_SUCCESS = 'CONCEPT_LIST_SUCCESS'
export const CONCEPT_LIST_FAILURE = 'CONCEPT_LIST_FAILURE'

export const CONCEPT_ACTION = 'CONCEPT_ACTION'