export const SET_AUTH = 'SET_AUTH'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const COURSE_SUBSCRIBE_REQUEST = 'COURSE_SUBSCRIBE_REQUEST'
export const COURSE_SUBSCRIBE_SUCCESS = 'COURSE_SUBSCRIBE_SUCCESS'
export const COURSE_SUBSCRIBE_FAILURE = 'COURSE_SUBSCRIBE_FAILURE'

export const SUBJECT_LIST_REQUEST = 'SUBJECT_LIST_REQUEST'
export const SUBJECT_LIST_SUCCESS = 'SUBJECT_LIST_SUCCESS'
export const SUBJECT_LIST_FAILURE = 'SUBJECT_LIST_FAILURE'


// The list of concepts to study
export const CONCEPT_LIST_REQUEST = 'CONCEPT_LIST_REQUEST'
export const CONCEPT_LIST_SUCCESS = 'CONCEPT_LIST_SUCCESS'
export const CONCEPT_LIST_FAILURE = 'CONCEPT_LIST_FAILURE'

// Set mode of conceptReader 
export const SET_MODE = 'SET_MODE'

// The Actions performed on concepts

export const CONCEPT_SKIP = 'CONCEPT_SKIP'

export const CONCEPT_DONE_REQUEST = 'CONCEPT_DONE_REQUEST'
export const CONCEPT_DONE_SUCCESS = 'CONCEPT_DONE_SUCCESS'
export const CONCEPT_DONE_FAILURE = 'CONCEPT_DONE_FAILURE'

export const CONCEPT_RIGHT_REQUEST = 'CONCEPT_RIGHT_REQUEST'
export const CONCEPT_RIGHT_SUCCESS = 'CONCEPT_RIGHT_SUCCESS'
export const CONCEPT_RIGHT_FAILURE = 'CONCEPT_RIGHT_FAILURE'

export const CONCEPT_WRONG_REQUEST = 'CONCEPT_WRONG_REQUEST'
export const CONCEPT_WRONG_SUCCESS = 'CONCEPT_WRONG_SUCCESS'
export const CONCEPT_WRONG_FAILURE = 'CONCEPT_WRONG_FAILURE'
