export const TOKEN_FOUND = 'TOKEN_FOUND'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const COURSE_SUBSCRIBE_REQUEST = 'COURSE_SUBSCRIBE_REQUEST'
export const COURSE_SUBSCRIBE_SUCCESS = 'COURSE_SUBSCRIBE_SUCCESS'
export const COURSE_SUBSCRIBE_FAILURE = 'COURSE_SUBSCRIBE_FAILURE'

export const SUBJECT_LIST_REQUEST = 'SUBJECT_LIST_REQUEST'
export const SUBJECT_LIST_SUCCESS = 'SUBJECT_LIST_SUCCESS'
export const SUBJECT_LIST_FAILURE = 'SUBJECT_LIST_FAILURE'

export const SUBJECT_DETAIL_REQUEST = 'SUBJECT_DETAIL_REQUEST'
export const SUBJECT_DETAIL_SUCCESS = 'SUBJECT_DETAIL_SUCCESS'
export const SUBJECT_DETAIL_FAILURE = 'SUBJECT_DETAIL_FAILURE'

export const SUBJECT_INDEX_REQUEST = 'SUBJECT_INDEX_REQUEST'
export const SUBJECT_INDEX_SUCCESS = 'SUBJECT_INDEX_SUCCESS'
export const SUBJECT_INDEX_FAILURE = 'SUBJECT_INDEX_FAILURE'


// The list of concepts to study
export const CONCEPT_LIST_REQUEST = 'CONCEPT_LIST_REQUEST'
export const CONCEPT_LIST_SUCCESS = 'CONCEPT_LIST_SUCCESS'
export const CONCEPT_LIST_FAILURE = 'CONCEPT_LIST_FAILURE'

// Single Concept
export const CONCEPT_VIEW_REQUEST = 'CONCEPT_VIEW_REQUEST'
export const CONCEPT_VIEW_SUCCESS = 'CONCEPT_VIEW_SUCCESS'
export const CONCEPT_VIEW_FAILURE = 'CONCEPT_VIEW_FAILURE'

// Set mode of conceptReader 
export const SET_MODE = 'SET_MODE'

// The Actions performed on concepts

export const CONCEPT_SKIP = 'CONCEPT_SKIP'

export const CONCEPT_READ_REQUEST = 'CONCEPT_READ_REQUEST'
export const CONCEPT_READ_SUCCESS = 'CONCEPT_READ_SUCCESS'
export const CONCEPT_READ_FAILURE = 'CONCEPT_READ_FAILURE'

export const CONCEPT_RIGHT_REQUEST = 'CONCEPT_RIGHT_REQUEST'
export const CONCEPT_RIGHT_SUCCESS = 'CONCEPT_RIGHT_SUCCESS'
export const CONCEPT_RIGHT_FAILURE = 'CONCEPT_RIGHT_FAILURE'

export const CONCEPT_WRONG_REQUEST = 'CONCEPT_WRONG_REQUEST'
export const CONCEPT_WRONG_SUCCESS = 'CONCEPT_WRONG_SUCCESS'
export const CONCEPT_WRONG_FAILURE = 'CONCEPT_WRONG_FAILURE'
